# Preliminaries

In [338]:
import numpy as np
import pandas as pd

# Physical properties and constraints
flow_rate = 20000 / 3600  # kg/hr to kg/s (A2)
T_hi, T_ho = 180, 96  # Inlet and outlet temperatures of oil (B3, C1)
T_ci, T_co = 25, 35  # Inlet and outlet temperatures of water (D2, D2+10)
mean_temp_water = (T_ci + T_co) / 2  # Mean temperature of water (30°C)
mean_temp_oil = (T_hi + T_ho) / 2  # Mean temperature of oil (138°C)

# Interpolated properties of water at mean temperature
T_water_props = [20, 40]  # Temperatures for interpolation (°C)
cp_water_props = [4.18, 4.19]  # Specific heat (kJ/kgK)
k_water_props = [0.598, 0.631]  # Thermal conductivity (W/mK)
rho_water_props = [998, 992]  # Density (kg/m³)
mu_water_props = [1.002e-3, 0.653e-3]  # Dynamic viscosity (Pa·s)

# Interpolated properties of oil at mean temperature
T_oil_props = [110, 140]  # Temperatures for interpolation (°C)
cp_oil_props = [2.25, 2.52]  # Specific heat (kJ/kgK)
k_oil_props = [0.14, 0.135]  # Thermal conductivity (W/mK)
rho_oil_props = [900, 850]  # Density (kg/m³)
mu_oil_props = [2.6734e10 * (110 + 273.15)**-3.5287 * 0.001, 2.6734e10 * (140 + 273.15)**-3.5287 * 0.001]  # Dynamic viscosity (Pa·s) cP to Pa.s = 0.001

# Interpolated values at mean temperature
cp_water = np.interp(mean_temp_water, T_water_props, cp_water_props)
cp_water = cp_water*1e3# J/kgK
k_water = np.interp(mean_temp_water, T_water_props, k_water_props)
rho_water = np.interp(mean_temp_water, T_water_props, rho_water_props)
mu_water = np.interp(mean_temp_water, T_water_props, mu_water_props)

cp_oil = np.interp(mean_temp_oil, T_oil_props, cp_oil_props)
cp_oil = cp_oil*1e3 #J/kgK
k_oil = np.interp(mean_temp_oil, T_oil_props, k_oil_props)
rho_oil = np.interp(mean_temp_oil, T_oil_props, rho_oil_props)
mu_oil = np.interp(mean_temp_oil, T_oil_props, mu_oil_props)

# Part 1
Q = flow_rate * (T_hi - T_ho)*cp_oil  # Heat transfer rate (W)
w = Q/((T_co - T_ci)*cp_water) # kg/s
R = (T_hi - T_ho)/(T_co - T_ci)
P = (T_co - T_ci)/(T_hi - T_ci)

# Correction factor (F) for LMTD
F = 0.95  # Typical for 1-shell pass, 2-tube pass configuration
LMTD = ((T_ho - T_co)-(T_hi - T_ci))/(np.log((T_ho-T_co)/(T_hi - T_ci)))
LMTD_corrected = F * LMTD

# Constraints
pressure_drop_limit = 15 * 6894.76  # Convert 15 psi to Pa

In [339]:
tube_lengths = np.array([2.44, 3.66, 4.88, 6.1])  # Extended tube lengths in meters (8, 12, 16, 20 ft)

In [340]:
# Extended TEMA-compliant dimensions for triangular pitch
tube_diameters_1 = 0.75*2.54/100 # Tube Outside Diameter meters D_o
shell_diameters_1 = [8,10,12,13.25,15.25,17.25,19.25,21.25,23.25,25,27,29,31,33,35,37,39]  # Shell ID (inner diameter) D_s
shell_diameters_1 = np.array(shell_diameters_1)*2.54/100 # meters
tube_pitch_ratios_1 = 1.25
tube_pitch_1 = tube_pitch_ratios_1 * tube_diameters_1 # meters
number_of_tubes_1 = [36,62,109,127,170,239,301,361,442,532,637,721,847,974,1102,1240,1377] # tube amount
tube_inner_diameters_1 = [0.482,0.510,0.532,0.560,0.584,0.606,0.620,0.634,0.652]
tube_inner_diameters_1 = np.array(tube_inner_diameters_1) * 2.54/100 # meters_ D_i

In [341]:
# Extended TEMA-compliant dimensions for triangular pitch
tube_diameters_2 = 1*2.54/100 # Tube Outside Diameter meters
shell_diameters_2 = shell_diameters_1 # Shell ID (inner diameter)
tube_pitch_ratios_2 = tube_pitch_ratios_1
tube_pitch_2 = tube_diameters_2 * tube_pitch_ratios_2 # meters
number_of_tubes_2 = [21,32,55,68,91,131,163,199,241,294,349,397,472,538,608,674,766] # tube amount
tube_inner_diameters_2 = [0.670,0.704,0.732,0.760,0.782,0.810,0.834,0.856,0.870,0.884,0.902]
tube_inner_diameters_2 = np.array(tube_inner_diameters_2) * 2.54/100 # meters

In [342]:
# Extended TEMA-compliant dimensions for triangular pitch
tube_diameters_3 = 1.5*2.54/100 # Tube Outside Diameter meter
shell_diameters_3 = [12,13.25,15.25,17.25,19.25,21.25,23.25,25,27,29,31,33,35,37,39]
shell_diameters_3 = np.array(shell_diameters_3)*2.54/100 # meters
tube_pitch_ratios_3 = tube_pitch_ratios_1
tube_pitch_3 = tube_diameters_3 * tube_pitch_ratios_3 # meters
number_of_tubes_3 = [18,27,36,48,61,76,95,115,136,160,184,215,246,275,307] # tube amount
tube_inner_diameters_3 = [0.482,0.510,0.532,0.560,0.584,0.606,0.620,0.634,0.652]
tube_inner_diameters_3 = np.array(tube_inner_diameters_3) * 2.54/100 # meters

In [343]:
# Extended TEMA-compliant dimensions for triangular pitch
tube_diameters_4 = tube_diameters_1 # Tube Outside Diameter meters
shell_diameters_4 = shell_diameters_1 # Shell ID (inner diameter)
tube_pitch_ratios_4 = 1.33
tube_pitch_4 = tube_diameters_4 * tube_pitch_ratios_4 # meters
number_of_tubes_4 = [37,61,92,109,151,203,262,316,384,470,559,630,745,856,970,1074,1206] # tube amount
tube_inner_diameters_4 = tube_inner_diameters_1 # meters
tube_inner_diameters_4 = [1.17,1.20,1.23,1.26,1.28,1.31,1.33,1.36,1.37,1.38,1.40]
tube_inner_diameters_4 = np.array(tube_inner_diameters_4) * 2.54/100 # meters

In [344]:
# Extended TEMA-compliant dimensions for triangular pitch
tube_diameters_5 = 1.25*2.54/100 # meters
shell_diameters_5 = [10,12,13.25,15.25,17.25,19.25,21.25,23.25,25,27,29,31,33,35,37,39]
shell_diameters_5 = np.array(shell_diameters_5)*2.54/100 # meters
tube_pitch_ratios_5 = 1.25
tube_pitch_5 = tube_diameters_5 * tube_pitch_ratios_5 # meters
number_of_tubes_5 = [20,32,38,54,69,95,117,140,170,202,235,275,315,357,407,449] # tube amount
tube_inner_diameters_5 = [0.920,0.954,0.982,1.01,1.03,1.06,1.08,1.11,1.12,1.13,1.15]
tube_inner_diameters_5 = np.array(tube_inner_diameters_5) * 2.54/100 # meters

# Optimization

## Initialization

* D_s shell_ID
* D_o Out Diameter of Tube
* D_i Inside Diameter of Tube
* P Tube Pitch

In [355]:
tube_diameters = None # D_o
shell_diameters = None # D_s
tube_pitch = None # meters P
tube_inner_diameters = None # D_i
number_of_tubes = None # Number of tubes


def retrieve_Values(num):
  global tube_diameters, shell_diameters, tube_pitch, tube_inner_diameters, number_of_tubes
  if num == 1:
    tube_diameters = tube_diameters_1
    shell_diameters = shell_diameters_1
    tube_pitch = tube_pitch_1
    tube_inner_diameters = tube_inner_diameters_1
    number_of_tubes = number_of_tubes_1
  elif num == 2:
    tube_diameters = tube_diameters_2
    shell_diameters = shell_diameters_2
    tube_pitch = tube_pitch_2
    tube_inner_diameters = tube_inner_diameters_2
    number_of_tubes = number_of_tubes_2
  elif num == 3:
    tube_diameters = tube_diameters_3
    shell_diameters = shell_diameters_3
    tube_pitch = tube_pitch_3
    tube_inner_diameters = tube_inner_diameters_3
    number_of_tubes = number_of_tubes_3
  elif num == 4:
    tube_diameters = tube_diameters_4
    shell_diameters = shell_diameters_4
    tube_pitch = tube_pitch_4
    tube_inner_diameters = tube_inner_diameters_4
    number_of_tubes = number_of_tubes_4
  elif num == 5:
    tube_diameters = tube_diameters_5
    shell_diameters = shell_diameters_5
    tube_pitch = tube_pitch_5
    tube_inner_diameters = tube_inner_diameters_5
    number_of_tubes = number_of_tubes_5
  else:
    print("False number given")

In [356]:
num = int(input("Please give me an integer from [1,2,3,4,5]: "))
retrieve_Values(num)

Please give me an integer from [1,2,3,4,5]: 5


In [357]:
tube_diameters = np.array([tube_diameters])
shell_diameters = np.array(shell_diameters)
tube_pitch = np.array([tube_pitch])
tube_inner_diameters = np.array(tube_inner_diameters)
number_of_tubes = np.array(number_of_tubes)

In [139]:
tube_diameters

array([0.01905])

In [140]:
shell_diameters

array([0.2032 , 0.254  , 0.3048 , 0.33655, 0.38735, 0.43815, 0.48895,
       0.53975, 0.59055, 0.635  , 0.6858 , 0.7366 , 0.7874 , 0.8382 ,
       0.889  , 0.9398 , 0.9906 ])

In [141]:
tube_pitch

array([0.0238125])

In [142]:
tube_inner_diameters

array([0.0122428, 0.012954 , 0.0135128, 0.014224 , 0.0148336, 0.0153924,
       0.015748 , 0.0161036, 0.0165608])

In [143]:
number_of_tubes

array([  36,   62,  109,  127,  170,  239,  301,  361,  442,  532,  637,
        721,  847,  974, 1102, 1240, 1377])

## Results

In [ ]:
#tube_diameters, shell_diameters, tube_pitch, tube_inner_diameters, number_of_tubes

In [50]:
w

27.899641577060923

In [348]:
num_of_tube_passes = np.arange(2,11,1)
Baffle_spacings = np.arange(2,11,1)
W = flow_rate # kg/s
w = w # water flow rate again kg/s
# PART 1-2-3-4 done they are in paper.
#count = 0

In [232]:
len(shell_diameters)

17

In [349]:
all_results = pd.DataFrame()

In [358]:

# Results storage
results = []

# Iterate over configurations
for i in range(len(shell_diameters)):
    for D_o in tube_diameters:
        for L_tube in tube_lengths:
            for D_i in tube_inner_diameters:
                for P in tube_pitch:
                    for n_t in num_of_tube_passes:
                        for B_t in Baffle_spacings:
                            #count += 1
                            D_s = shell_diameters[i]
                            #print(D_s)
                            N_t = number_of_tubes[i]
                            #print(N_t)
                            # Part-5 (Area for Cross-Flow) & (For Flow area obtain D_i)
                            a_t = (np.pi * D_i**2) / 4 # Flow area per tube m²
                            B = B_t*D_s/10
                            S_c = (P - D_o)*B*(D_s/P)
                            G_c = W/S_c

                            # Part-6 (Area for Baffle Window) & (Flow area per pass)
                            A_t = N_t*a_t/n_t
                            N_b = N_t // 4
                            f_b = 0.1955 # Optional idk what optional means
                            S_b = (f_b*(np.pi*(D_s)**2)/4) - N_b*(np.pi*(D_o)**2)/4
                            G_b = W/S_b

                            # Part-7 Mass Velocity & Average Velocity
                            if np.isnan(G_c) or np.isnan(G_b) or G_c < 0 or G_b < 0:
                                continue  # Skip to the next iteration if G_c or G_b is NaN or less than 0
                            G_e = (G_c*G_b)**(1/2)
                            if np.isnan(G_e):
                                continue
                            v = w/(A_t*rho_water)

                            # Part-8 Reynolds Shell and Tube
                            Re_s = D_o*G_e/mu_oil
                            #print(Re_s,D_i,D_o,D_s,N_t,B,S_c,S_b,G_c,G_b,G_e)
                            #print("AAAAAAA")
                            Re_t = rho_water*v*D_i/mu_water

                            # Part-9 Prandtl Number for Shell and Tube
                            Pr_s = cp_oil*mu_oil/k_oil
                            Pr_t = cp_water*mu_water/k_water

                            # Conditions
                            if (Re_t >1e4) & (Re_t < 5*1e6) & (Pr_t > 0.5) & (Pr_t < 2*1e3):
                                Re_d = Re_t
                            elif (Re_t >2.3e3) & (Re_t < 1e4) & (Pr_t > 0.5) & (Pr_t < 2*1e3):
                                Re_d = Re_t - 1000
                            else:
                                continue

                            eps_over_D = 0 # for clean pipe
                            A = (eps_over_D/2.5497)**(1.1098) + (7.149/Re_t)**(0.8981)

                            f = (1/(-4*np.log10((eps_over_D/3.7065) - (5.0452/Re_t)*np.log10(A))))**(1/2)

                            ## Part 10
                            # Gnielinski Eqn. for tube side
                            Nu_D = ((f/2)*(Re_d)*Pr_t)/(1 + 12.7*(f/2)**(1/2) * (Pr_t**(2/3) - 1))# h_i*D_i/k

                            h_i = Nu_D*k_water/D_i # Tube side
                            h_io = h_i*D_i/D_o # Shell side

                            # Donohue Eqn. for shell side
                            h_s_over_phi_s = (k_oil/D_o)*0.2*((D_o*G_e/mu_oil)**(0.6)) *((cp_oil*mu_oil/k_oil)**(0.33))

                            ## Part 11
                            t_w = mean_temp_water + ((h_s_over_phi_s)/(h_io + h_s_over_phi_s))*(mean_temp_oil - mean_temp_water)
                            mu_w = 2.6734e10 * (t_w + 273.15)**-3.5287 * 0.001
                            ## Part 12 Find mu_water
                            phi_s = (mu_oil/mu_w)**(0.14)
                            ## Part 13 Corrected Coefficient
                            h_o = h_s_over_phi_s*phi_s
                            ## Part 14 Clean Overall Coefficient
                            U_c = (h_io*h_o)/(h_io + h_o)
                            ## Part 15 Design Overall Coefficient
                            A = np.pi*D_o*L_tube*N_t
                            U_d = Q/(A*LMTD_corrected)

                            R_d = (U_c - U_d)/(U_c*U_d)

                            ## Pressure Step

                            # We assumed Triangular pitch and used table based on it from KERN
                            D_h = 4*((P/2) *(0.86*P) - 0.5*0.25*np.pi*((D_o)**2))/(0.5*np.pi*D_o)
                            Re = D_h*G_c/mu_oil
                            if Re > 400:
                                ff = 1.7789*(Re**(-0.195868))
                            else:
                                continue
                            ## N+1 = L_tube/B
                            # Shell Side
                            delta_P_shell = ((ff)*((G_c)**(2)) * D_s * L_tube)/(2*D_h*phi_s*rho_oil*B)
                            if delta_P_shell > pressure_drop_limit:
                                continue
                            # Tube Side
                            # Inside tubes
                            delta_P_t = ((4*ff*L_tube*n_t)/(D_i))*rho_water*((v**2)/2)
                            # Tube side returns
                            delta_P_r = 4*n_t*(rho_water*(v**(2))/2)
                            # Total
                            delta_P_total = delta_P_t + delta_P_r
                            if delta_P_total > pressure_drop_limit:
                                continue

                            # Store results
                            results.append({
                                "Tube Outside Diameter (m)": D_o,
                                "Shell Diameter (m)": D_s,
                                "Tube Length (m)": L_tube,
                                "Number of tubes": N_t,
                                "Number of Baffle": N_b,
                                "Tube Inner Diameter (m)": D_i,
                                "Tube Pitch ": P,
                                "Velocity Tube (m/s)": v,
                                "Reynolds Tube": Re_t,
                                "Heat Transfer Coefficient Tube (W/m²K)": h_io,
                                "Pressure Drop Tube (Pa)": delta_P_total,
                                "Velocity Shell (m/s)": G_e,
                                "Reynolds Shell": Re_s,
                                "Heat Transfer Coefficient Shell (W/m²K)": h_o,
                                "Clean Overall Heat Transfer Coefficient (W/m²K)": U_c,
                                "Overall Heat Transfer Coefficient (W/m²K)": U_d,
                                "Heat Transfer Rate (W)": Q
                                })

# Convert results to DataFrame
results_df = pd.DataFrame(results)
all_results = pd.concat([all_results, results_df])
# Find the optimal configuration
optimal_config = results_df.sort_values(by="Overall Heat Transfer Coefficient (W/m²K)", ascending=False).iloc[0]

# Output results
print("Optimal Configuration:")
print(optimal_config)

# Save results to a CSV file
results_df.to_csv(f"heat_exchanger_optimization_results{num}.csv", index=False)


Optimal Configuration:
Tube Outside Diameter (m)                          3.175000e-02
Shell Diameter (m)                                 5.397500e-01
Tube Length (m)                                    2.440000e+00
Number of tubes                                    1.170000e+02
Number of Baffle                                   2.900000e+01
Tube Inner Diameter (m)                            2.819400e-02
Tube Pitch                                         3.968750e-02
Velocity Tube (m/s)                                7.677440e-01
Reynolds Tube                                      2.602724e+04
Heat Transfer Coefficient Tube (W/m²K)             3.512599e+04
Pressure Drop Tube (Pa)                            1.032440e+05
Velocity Shell (m/s)                               3.487818e+02
Reynolds Shell                                     6.917643e+02
Heat Transfer Coefficient Shell (W/m²K)            2.429847e+02
Clean Overall Heat Transfer Coefficient (W/m²K)    2.413154e+02
Overall Heat Tran

In [359]:
# Find the optimal configuration
optimal_config_all = all_results.sort_values(by="Overall Heat Transfer Coefficient (W/m²K)", ascending=False).iloc[0]

# Output results
print("Optimal Configuration:")
print(optimal_config_all)

Optimal Configuration:
Tube Outside Diameter (m)                          1.905000e-02
Shell Diameter (m)                                 3.048000e-01
Tube Length (m)                                    2.440000e+00
Number of tubes                                    9.200000e+01
Number of Baffle                                   2.300000e+01
Tube Inner Diameter (m)                            3.505200e-02
Tube Pitch                                         2.533650e-02
Velocity Tube (m/s)                                6.316874e-01
Reynolds Tube                                      2.662380e+04
Heat Transfer Coefficient Tube (W/m²K)             5.984132e+04
Pressure Drop Tube (Pa)                            6.107788e+04
Velocity Shell (m/s)                               5.380198e+02
Reynolds Shell                                     6.402563e+02
Heat Transfer Coefficient Shell (W/m²K)            3.865675e+02
Clean Overall Heat Transfer Coefficient (W/m²K)    3.840864e+02
Overall Heat Tran